/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Museum_new.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Museum(props) {
  const { nodes, materials } = useGLTF('models/Museum_new.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <group position={[1.679, 3.994, -0.222]} rotation={[-0.179, 0, 0]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[1.679, 3.994, -11.822]} rotation={[-0.179, 0, 0]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder_4.geometry} material={materials['Material.002']} />
      </group>
      <group position={[2.877, 3.994, -7.535]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder_5.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder_6.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.927, 3.994, -7.535]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder_7.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder_8.geometry} material={materials['Material.002']} />
      </group>
      <group position={[2.877, 3.994, 2.077]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder_9.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder_10.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.927, 3.994, 2.077]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder_11.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder_12.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Cube002.geometry} material={materials['Wood vanished']} position={[0, 2.061, 0]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524.geometry} material={materials.dab3f60e50f26f0116e837d544be3524} position={[-4.976, 1.809, -0.299]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524001.geometry} material={materials.dab3f60e50f26f0116e837d544be3524} position={[4.967, 1.827, -0.286]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524002.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.003']} position={[-4.976, 1.809, -0.299]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524003.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.002']} position={[-4.976, 1.809, -0.299]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524004.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.001']} position={[-4.976, 1.809, -0.299]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524005.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.001']} position={[4.967, 1.827, -0.286]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524006.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.003']} position={[4.967, 1.827, -0.88]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524007.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.002']} position={[4.967, 1.827, -0.286]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.003']} position={[-1.87, 1.45, -2.621]} rotation={[Math.PI / 2, 0, 0.435]} scale={[1, 1, 1.233]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.003']} position={[1.379, 1.45, -2.621]} rotation={[Math.PI / 2, 0, -0.497]} scale={[1, 1, 1.233]} />
      <mesh geometry={nodes.Circle.geometry} material={nodes.Circle.material} position={[0, 2.061, -13.946]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Marble} position={[0, 2.061, 0]} />
      <group position={[0, 2.061, 0]}>
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.Marble} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials['Material.004']} />
      </group>
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.005']} position={[1.379, 1.45, 14.785]} rotation={[Math.PI / 2, 0, -0.497]} scale={[1, 1, 1.233]} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['Material.005']} position={[-1.87, 1.45, 14.785]} rotation={[Math.PI / 2, 0, 0.435]} scale={[1, 1, 1.233]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524008.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.004']} position={[4.967, 1.827, 17.052]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524009.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.005']} position={[4.967, 1.827, 17.052]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524010.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.006']} position={[4.967, 1.827, 17.052]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524011.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.006']} position={[-4.976, 1.809, 17.039]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524012.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.004']} position={[-4.976, 1.809, 17.039]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524013.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.005']} position={[-4.976, 1.809, 17.039]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524014.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.007']} position={[4.967, 1.827, 17.052]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524015.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.007']} position={[-4.976, 1.809, 17.039]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <group position={[-2.927, 3.994, 19.415]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.007']} />
      </group>
      <group position={[2.877, 3.994, 19.415]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder001_4.geometry} material={materials['Material.007']} />
      </group>
      <group position={[-2.927, 3.994, 9.803]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder001_5.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder001_6.geometry} material={materials['Material.007']} />
      </group>
      <group position={[2.877, 3.994, 9.803]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder001_7.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder001_8.geometry} material={materials['Material.007']} />
      </group>
      <group position={[1.679, 3.994, 5.516]} rotation={[-0.179, 0, 0]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder001_9.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder001_10.geometry} material={materials['Material.007']} />
      </group>
      <group position={[1.679, 3.994, 17.116]} rotation={[-0.179, 0, 0]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder001_11.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder001_12.geometry} material={materials['Material.007']} />
      </group>
      <mesh geometry={nodes.Cube005.geometry} material={materials.Material} position={[0, 2.061, 17.338]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Wood vanished.001']} position={[0, 2.061, 17.338]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.008']} position={[0, 0, 17.338]} />
      <mesh geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} position={[0, 2.061, 3.392]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['Material.005']} position={[1.379, 1.45, 31.965]} rotation={[Math.PI / 2, 0, -0.497]} scale={[1, 1, 1.233]} />
      <mesh geometry={nodes.Plane006.geometry} material={materials['Material.005']} position={[-1.87, 1.45, 31.965]} rotation={[Math.PI / 2, 0, 0.435]} scale={[1, 1, 1.233]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524016.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.004']} position={[4.967, 1.827, 34.233]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524017.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.005']} position={[4.967, 1.827, 34.233]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524018.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.006']} position={[4.967, 1.827, 34.233]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524019.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.006']} position={[-4.976, 1.809, 34.22]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524020.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.004']} position={[-4.976, 1.809, 34.22]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524022.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.007']} position={[4.967, 1.827, 34.233]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524023.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.007']} position={[-4.976, 1.809, 34.22]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <group position={[-2.927, 3.994, 36.595]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder002_2.geometry} material={materials['Material.007']} />
      </group>
      <group position={[2.877, 3.994, 36.595]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder002_3.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder002_4.geometry} material={materials['Material.007']} />
      </group>
      <group position={[-2.927, 3.994, 26.983]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder002_5.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder002_6.geometry} material={materials['Material.007']} />
      </group>
      <group position={[2.877, 3.994, 26.983]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder002_7.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder002_8.geometry} material={materials['Material.007']} />
      </group>
      <group position={[1.679, 3.994, 22.697]} rotation={[-0.179, 0, 0]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder002_9.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder002_10.geometry} material={materials['Material.007']} />
      </group>
      <group position={[1.679, 3.994, 34.296]} rotation={[-0.179, 0, 0]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder002_11.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder002_12.geometry} material={materials['Material.007']} />
      </group>
      <mesh geometry={nodes.Cube009.geometry} material={materials.Material} position={[0, 2.061, 34.672]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Wood vanished.001']} position={[0, 2.061, 34.518]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.008']} position={[0, 0, 34.518]} />
      <mesh geometry={nodes.Circle002.geometry} material={nodes.Circle002.material} position={[0, 2.061, 20.572]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['Material.005']} position={[1.379, 1.45, 49.3]} rotation={[Math.PI / 2, 0, -0.497]} scale={[1, 1, 1.233]} />
      <mesh geometry={nodes.Plane008.geometry} material={materials['Material.005']} position={[-1.87, 1.45, 49.3]} rotation={[Math.PI / 2, 0, 0.435]} scale={[1, 1, 1.233]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524024.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.004']} position={[4.967, 1.827, 51.567]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524025.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.005']} position={[4.967, 1.827, 51.567]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524026.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.006']} position={[4.967, 1.827, 51.567]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524027.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.006']} position={[-4.976, 1.809, 51.554]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524028.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.004']} position={[-4.976, 1.809, 51.554]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524029.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.005']} position={[-4.976, 1.809, 51.554]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524030.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.007']} position={[4.967, 1.827, 51.567]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524031.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.007']} position={[-4.976, 1.809, 51.554]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <group position={[-2.927, 3.994, 53.929]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Material.007']} />
      </group>
      <group position={[2.877, 3.994, 53.929]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder003_3.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder003_4.geometry} material={materials['Material.007']} />
      </group>
      <group position={[-2.927, 3.994, 44.317]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder003_5.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder003_6.geometry} material={materials['Material.007']} />
      </group>
      <group position={[2.877, 3.994, 44.317]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder003_7.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder003_8.geometry} material={materials['Material.007']} />
      </group>
      <group position={[1.679, 3.994, 40.031]} rotation={[-0.179, 0, 0]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder003_9.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder003_10.geometry} material={materials['Material.007']} />
      </group>
      <group position={[1.679, 3.994, 51.63]} rotation={[-0.179, 0, 0]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder003_11.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder003_12.geometry} material={materials['Material.007']} />
      </group>
      <mesh geometry={nodes.Cube013.geometry} material={materials.Material} position={[0, 2.061, 51.853]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Wood vanished.001']} position={[0, 2.061, 51.853]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials['Material.008']} position={[0, 0, 51.853]} />
      <mesh geometry={nodes.Circle003.geometry} material={nodes.Circle003.material} position={[0, 2.061, 37.906]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Plane009.geometry} material={materials['Material.005']} position={[1.379, 1.45, 66.634]} rotation={[Math.PI / 2, 0, -0.497]} scale={[1, 1, 1.233]} />
      <mesh geometry={nodes.Plane010.geometry} material={materials['Material.005']} position={[-1.87, 1.45, 66.634]} rotation={[Math.PI / 2, 0, 0.435]} scale={[1, 1, 1.233]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524032.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.004']} position={[4.967, 1.827, 68.901]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524033.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.005']} position={[4.967, 1.827, 68.901]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524034.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.006']} position={[4.967, 1.827, 68.901]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524035.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.006']} position={[-4.976, 1.809, 68.888]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524036.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.004']} position={[-4.976, 1.809, 68.888]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524037.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.005']} position={[-4.976, 1.809, 68.888]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524038.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.007']} position={[4.967, 1.827, 68.901]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524039.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.007']} position={[-4.976, 1.809, 68.888]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <group position={[-2.927, 3.994, 71.264]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={materials['Material.007']} />
      </group>
      <group position={[2.877, 3.994, 71.264]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder004_3.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder004_4.geometry} material={materials['Material.007']} />
      </group>
      <group position={[-2.927, 3.994, 61.651]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder004_5.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder004_6.geometry} material={materials['Material.007']} />
      </group>
      <group position={[2.877, 3.994, 61.651]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder004_7.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder004_8.geometry} material={materials['Material.007']} />
      </group>
      <group position={[1.679, 3.994, 57.365]} rotation={[-0.179, 0, 0]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder004_9.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder004_10.geometry} material={materials['Material.007']} />
      </group>
      <group position={[1.679, 3.994, 68.964]} rotation={[-0.179, 0, 0]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder004_11.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder004_12.geometry} material={materials['Material.007']} />
      </group>
      <mesh geometry={nodes.Cube017.geometry} material={materials.Material} position={[0, 2.061, 69.187]} />
      <mesh geometry={nodes.Cube018.geometry} material={materials['Wood vanished.001']} position={[0, 2.061, 69.187]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials['Material.008']} position={[0, 0, 69.187]} />
      <mesh geometry={nodes.Circle004.geometry} material={nodes.Circle004.material} position={[0, 2.061, 55.24]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Plane011.geometry} material={materials['Material.005']} position={[1.379, 1.45, 83.968]} rotation={[Math.PI / 2, 0, -0.497]} scale={[1, 1, 1.233]} />
      <mesh geometry={nodes.Plane012.geometry} material={materials['Material.005']} position={[-1.87, 1.45, 83.968]} rotation={[Math.PI / 2, 0, 0.435]} scale={[1, 1, 1.233]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524040.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.004']} position={[4.967, 1.827, 86.235]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524041.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.005']} position={[4.967, 1.827, 86.235]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524042.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.006']} position={[4.967, 1.827, 86.235]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524043.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.006']} position={[-4.976, 1.809, 86.222]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524044.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.004']} position={[-4.976, 1.809, 86.222]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524045.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.005']} position={[-4.976, 1.809, 86.222]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524046.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.007']} position={[4.967, 1.827, 86.235]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524047.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.007']} position={[-4.976, 1.809, 86.222]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.dab3f60e50f26f0116e837d544be3524021.geometry} material={materials['dab3f60e50f26f0116e837d544be3524.005']} position={[52.002, 0, 0]} />
      </mesh>
      <group position={[-2.927, 3.994, 88.598]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder005_2.geometry} material={materials['Material.007']} />
      </group>
      <group position={[2.877, 3.994, 88.598]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder005_3.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder005_4.geometry} material={materials['Material.007']} />
      </group>
      <group position={[-2.927, 3.994, 78.986]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder005_5.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder005_6.geometry} material={materials['Material.007']} />
      </group>
      <group position={[2.877, 3.994, 78.986]} rotation={[-Math.PI / 2, -1.392, -Math.PI / 2]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder005_7.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder005_8.geometry} material={materials['Material.007']} />
      </group>
      <group position={[1.679, 3.994, 74.699]} rotation={[-0.179, 0, 0]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder005_9.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder005_10.geometry} material={materials['Material.007']} />
      </group>
      <group position={[1.679, 3.994, 86.298]} rotation={[-0.179, 0, 0]} scale={-0.086}>
        <mesh geometry={nodes.Cylinder005_11.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder005_12.geometry} material={materials['Material.007']} />
      </group>
      <group position={[0, 2.061, 86.521]}>
        <mesh geometry={nodes.Cube021_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube021_2.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.Cube022.geometry} material={materials['Wood vanished.001']} position={[0, 2.061, 86.521]} />
      <mesh geometry={nodes.Cube024.geometry} material={materials['Material.008']} position={[0, 0, 86.521]} />
      <mesh geometry={nodes.Circle005.geometry} material={nodes.Circle005.material} position={[0, 2.061, 72.574]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <group position={[-4.731, 2.968, 2.598]} scale={[0.531, 2.994, 0.663]}>
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['Material.013']} />
      </group>
      <group position={[4.777, 2.968, 2.598]} scale={[0.531, 2.994, 0.663]}>
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['Material.013']} />
      </group>
      <group position={[-4.731, 2.968, 19.742]} scale={[0.531, 2.994, 0.663]}>
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['Material.013']} />
      </group>
      <group position={[4.777, 2.968, 19.742]} scale={[0.531, 2.994, 0.663]}>
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['Material.013']} />
      </group>
      <group position={[-4.731, 2.968, 36.886]} scale={[0.531, 2.994, 0.663]}>
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['Material.013']} />
      </group>
      <group position={[4.777, 2.968, 36.886]} scale={[0.531, 2.994, 0.663]}>
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['Material.013']} />
      </group>
      <group position={[-4.731, 2.968, 54.404]} scale={[0.531, 2.994, 0.663]}>
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['Material.013']} />
      </group>
      <group position={[4.777, 2.968, 54.404]} scale={[0.531, 2.994, 0.663]}>
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['Material.013']} />
      </group>
      <group position={[-4.731, 2.968, 71.922]} scale={[0.531, 2.994, 0.663]}>
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['Material.013']} />
      </group>
      <group position={[4.777, 2.968, 71.922]} scale={[0.531, 2.994, 0.663]}>
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['Material.013']} />
      </group>
      <group position={[-4.731, 2.968, 89.159]} scale={[0.531, 2.994, 0.663]}>
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['Material.013']} />
      </group>
      <group position={[4.777, 2.968, 89.159]} scale={[0.531, 2.994, 0.663]}>
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['Material.013']} />
      </group>
      <group position={[0, 2.061, 0]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.003']} />
        <group position={[-5.02, 0, -6.156]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.629, -0.251, -1.018]}>
          <mesh geometry={nodes.Plane018_1.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Plane018_2.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Plane018_3.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Plane013.geometry} material={materials['Material.009']} />
        </group>
        <group position={[5.02, 0, -6.156]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.629, -0.251, -1.018]}>
          <mesh geometry={nodes.Plane020_1.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Plane020_2.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Plane020_3.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Plane015.geometry} material={materials['Material.009']} />
        </group>
      </group>
      <group position={[0, 2.061, 17.368]}>
        <mesh geometry={nodes.Cube027_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube027_2.geometry} material={materials['Material.003']} />
        <group position={[-5.02, 0, -6.156]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.629, -0.251, -1.018]}>
          <mesh geometry={nodes.Plane022_1.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Plane022_2.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Plane022_3.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Plane017.geometry} material={materials['Material.009']} />
        </group>
        <group position={[5.02, 0, -6.156]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.629, -0.251, -1.018]}>
          <mesh geometry={nodes.Plane024_1.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Plane024_2.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Plane024_3.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Plane019.geometry} material={materials['Material.009']} />
        </group>
      </group>
      <group position={[0, 2.061, 34.736]}>
        <mesh geometry={nodes.Cube028_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube028_2.geometry} material={materials['Material.003']} />
        <group position={[-5.02, 0, -6.156]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.629, -0.251, -1.018]}>
          <mesh geometry={nodes.Plane026_1.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Plane026_2.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Plane026_3.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Plane021.geometry} material={materials['Material.009']} />
        </group>
        <group position={[5.02, 0, -6.156]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.629, -0.251, -1.018]}>
          <mesh geometry={nodes.Plane028_1.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Plane028_2.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Plane028_3.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Plane023.geometry} material={materials['Material.009']} />
        </group>
      </group>
      <group position={[0, 2.061, 52.104]}>
        <mesh geometry={nodes.Cube029_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube029_2.geometry} material={materials['Material.003']} />
        <group position={[-5.02, 0, -6.156]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.629, -0.251, -1.018]}>
          <mesh geometry={nodes.Plane030_1.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Plane030_2.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Plane030_3.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Plane025.geometry} material={materials['Material.009']} />
        </group>
        <group position={[5.02, 0, -6.156]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.629, -0.251, -1.018]}>
          <mesh geometry={nodes.Plane032_1.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Plane032_2.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Plane032_3.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Plane027.geometry} material={materials['Material.009']} />
        </group>
      </group>
      <group position={[0, 2.061, 69.472]}>
        <mesh geometry={nodes.Cube030_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube030_2.geometry} material={materials['Material.003']} />
        <group position={[-5.02, 0, -6.156]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.629, -0.251, -1.018]}>
          <mesh geometry={nodes.Plane034_1.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Plane034_2.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Plane034_3.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Plane029.geometry} material={materials['Material.009']} />
        </group>
        <group position={[5.02, 0, -6.156]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.629, -0.251, -1.018]}>
          <mesh geometry={nodes.Plane036.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Plane036_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Plane036_2.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Plane031.geometry} material={materials['Material.009']} />
        </group>
      </group>
      <group position={[0, 2.061, 86.84]}>
        <mesh geometry={nodes.Cube031_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube031_2.geometry} material={materials['Material.003']} />
        <group position={[-5.02, 0, -6.156]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.629, -0.251, -1.018]}>
          <mesh geometry={nodes.Plane038.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Plane038_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Plane038_2.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Plane033.geometry} material={materials['Material.009']} />
        </group>
        <group position={[5.02, 0, -6.156]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.629, -0.251, -1.018]}>
          <mesh geometry={nodes.Plane040.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Plane040_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Plane040_2.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Plane035.geometry} material={materials['Material.009']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/Museum_new.gltf')
